#!/bin/bash

# remove the existing builds.
rm -rf $PWD/build/
rm -rf $PWD/1.log
rm -rf $PWD/2.log
rm -rf $PWD/3.log
rm -rf $PWD/4.log


# OSS 
swift/utils/build-script --ios --tvos --watchos --test --validation-test --release --assertions --test-optimized -- --verbose-build=1 --build-ninja '--swift-sdks=OSX;IOS;IOS_SIMULATOR;TVOS;TVOS_SIMULATOR;WATCHOS;WATCHOS_SIMULATOR' --build-swift-static-stdlib=1 --compiler-vendor=apple --darwin-crash-reporter-client=0 --install-swift=1 --install-destdir=/Users/buildnode/jenkins/workspace/oss-swift_tools-RA_stdlib-RDA_test-simulator/install --installable-package=/Users/buildnode/jenkins/workspace/oss-swift_tools-RA_stdlib-RDA_test-simulator/oss-swift_tools-RA_stdlib-RDA_test-simulator-b284.tar.gz --reconfigure '--swift-install-components=compiler;clang-builtin-headers;stdlib;sdk-overlay;editor-integration;tools;testsuite-tools' --swift-stdlib-build-type=RelWithDebInfo --swift-stdlib-enable-assertions=true --sil-verify-all


echo "Running: #1" >> 1.log 2>&1
$PWD/swift/utils/build-script --ios-all --tvos-all --watchos-all --test --validation-test --release --assertions --test-optimized -- --verbose-build=1 --build-ninja  --skip-test-tvos --skip-test-watchos '--swift-sdks=OSX;IOS;IOS_SIMULATOR;TVOS;TVOS_SIMULATOR;WATCHOS;WATCHOS_SIMULATOR' --build-swift-static-stdlib=1 --compiler-vendor=apple --darwin-crash-reporter-client=0  --swift-stdlib-build-type=RelWithDebInfo --swift-stdlib-enable-assertions=false --sil-verify-all --skip-test-ios-device --skip-test-tvos-device --skip-test-watchos-device >> 1.log 2>&1

echo "Running: #2" >> 2.log 2>&1
swift/utils/build-script --ios --tvos --test --validation-test --build-subdir=buildbot_incremental_asan --release-debuginfo --assertions -- --reconfigure --verbose-build=1 --build-ninja --build-swift-static-stdlib=0 --compiler-vendor=apple --skip-build-ios --skip-test-ios --skip-build-tvos --skip-test-tvos --skip-build-watchos --skip-test-watchos --enable-asan >> 2.log 2>&1

echo "Running: #3" >> 3.log 2>&1
swift/utils/build-script  --ios --tvos --test --validation-test --build-subdir=buildbot_incremental --release --assertions  -- --reconfigure --verbose-build=1 --build-ninja --build-swift-static-stdlib=0 --compiler-vendor=apple --skip-test-ios --skip-test-tvos --skip-test-watchos >> 3.log 2>&1

echo "Running: #4" >> 4.log 2>&1
$PWD/swift/utils/build-script --ios-all --tvos-all --watchos-all --test --validation-test --release --assertions --test-optimized -- --verbose-build=1 --build-ninja  --skip-test-tvos --skip-test-watchos '--swift-sdks=OSX;IOS;IOS_SIMULATOR;TVOS;TVOS_SIMULATOR;WATCHOS;WATCHOS_SIMULATOR' --build-swift-static-stdlib=1 --compiler-vendor=apple --darwin-crash-reporter-client=0  --swift-stdlib-build-type=RelWithDebInfo --swift-stdlib-enable-assertions=true --sil-verify-all --skip-test-ios-device --skip-test-tvos-device --skip-test-watchos-device >> 4.log 2>&1



